### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by moul** [comment]
:kiss:

**Comment by moul** [comment]
If you add a boolean in credentials.yml to disable slideshare_upload completely without raising anything OK, because in my case, I want to disable the SlideShare upload, so I can work on LinkedIn and rendering parts and I don't want an exception

**Comment by sylvainkalache** [comment]
I'll do a boolean then

**Comment by sylvainkalache** [comment]
Done https://github.com/sylvainkalache/visual_resume/commit/fe0da7309d33d9786c53a49673a32caf99f86f8b

**Pull request closed without merging**
